### PR TITLE
Updates for iOS 11 and Swift 4

### PR DESCRIPTION
**Pull request by maciejtrybilo**

### CODE REVIEW

**Comment by maciejtrybilo** [comment]
I'll be optimistic and assume your Bitrise doesn't use Xcode 9 yet? :)

**Comment by julienregnauld-je** [comment]
@maciejtrybilo exactly, still using Xcode 8!  thanks for the PR by the way 😁

**Comment by maciejtrybilo** [comment]
Cool, would you guys consider putting up a swift4 branch for the folks who already moved? Or releasing a new version with this and constraining to the current one in your Podfile.

**Review by federicocappelli-je — APPROVED** [review]

**Comment by federicocappelli-je** [comment]
@maciejtrybilo Version 1.0.1 (XCode 9.1 | Swift 4 | iOS 11) published.

**Pull request merged**
