### PR TITLE
Add animated parameter

### PR DESCRIPTION
**Pull request by gigisommo**
This PR adds the possibility to pass an animated parameter to present and remove view controllers with or without animation.

I moved the supported operating system to iOS 11.

This PR bumps the major version (to 5.0.0)

### CODE REVIEW

**Comment by richardtop** [comment]
Hi, thanks for the pull request, however, for me it's important to support iOS 9+. Could you please apply the changes without bumping the deployment target?

What are the new APIs that are critical for this feature to work?

**Comment by gigisommo** [comment]
I'm sorry for that, but we chose to move all our deployment target to iOS 11. As far as I know there aren't APIs that prevent it to work on iOS 9, but we're trying to follow Apple's advice on supporting just the iOS major version before the current major one. I would advise you to fork it(and change the deployment target) because we're not going to work on compatibility for versions previous to iOS 11 not just in terms of API, but also considering testing and eventual bug fixes.

**Comment by richardtop** [comment]
@gigisommo Could you then not bump it in this update? For example, mention that the officially supported version is 11+, but keep the one specified in the `.podspec` as 9+.

That would make it able to install for me, without the need to fork and do the extra maintenance.

**Comment by richardtop** [comment]
Alternatively, bump the version to iOS 11 **after** this pull request gets merged, during the next release of the library.

We both are happy:
1. You keep iOS 11+ as the minimum deployment target
2. I incorporate the change I need in my project without forking it.

**Comment by gigisommo** [comment]
Yes, it make sense. I'll open another PR to remove the support to iOS 9 after this one. I'm reverting the deployment target changes

**Comment by richardtop** [comment]
Thanks a lot!

**Comment by gigisommo** [comment]
You're welcome. Consider pinning the version to the 5.0.0 because we're going to change the deployment target soon.

**Comment by richardtop** [comment]
Fine. We're too :) It's just now I have to support iOS 9.

**Review by junaidyounus-je — APPROVED** [review]

**Pull request merged**
